/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modlue10labstorybook;

/**
 *
 * @author jcwm2
 */
public class EndFrame extends javax.swing.JFrame {
    private StorybookModel myModel;
    /**
     * Creates new form NewJFrame
     */
    public EndFrame( StorybookModel myModel) {
        initComponents();
        this.myModel = myModel;     
        welcomeLabel.setText("Welcome, " + myModel.getUserName() + ".");
        crimeLabel1.setText("You have been accused of " + myModel.getCrime() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        crimeLabel = new javax.swing.JLabel();
        crimeLabel1 = new javax.swing.JLabel();
        verdict = new javax.swing.JLabel();
        leftDoorButton = new javax.swing.JButton();
        rightDoorButton = new javax.swing.JButton();
        exitTribunal = new javax.swing.JButton();
        nextTrial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Welcome");

        crimeLabel1.setText("crime");

        verdict.setText("Pick a door to determine your verdict.");

        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Door.GIF"))); // NOI18N
        leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorButtonActionPerformed(evt);
            }
        });

        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Door.GIF"))); // NOI18N
        rightDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorButtonActionPerformed(evt);
            }
        });

        exitTribunal.setText("Exit Tribunal");
        exitTribunal.setEnabled(false);
        exitTribunal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTribunalActionPerformed(evt);
            }
        });

        nextTrial.setText("Next Trial -->");
        nextTrial.setEnabled(false);
        nextTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTrialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verdict)
                            .addComponent(crimeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leftDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitTribunal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextTrial)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crimeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verdict)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftDoorButton)
                    .addComponent(rightDoorButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(crimeLabel)
                        .addGap(219, 219, 219)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextTrial)
                    .addComponent(exitTribunal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tiger.GIF")));
        verdict.setText("You are GUILTY! Prepare to be eaten!");
        exitTribunal.setEnabled(true);
        nextTrial.setEnabled(true);
        rightDoorButton.setEnabled(false);
    }//GEN-LAST:event_leftDoorButtonActionPerformed

    private void rightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorButtonActionPerformed
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lady.GIF")));
        verdict.setText("You are Innocent! Here is a JPEG of a lady I found online.");
        exitTribunal.setEnabled(true);
        nextTrial.setEnabled(true);
        leftDoorButton.setEnabled(false);
    }//GEN-LAST:event_rightDoorButtonActionPerformed

    private void exitTribunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTribunalActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitTribunalActionPerformed

    private void nextTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrialActionPerformed
        StartFrame myStartFrame = new StartFrame(myModel);
        myStartFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextTrialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crimeLabel;
    private javax.swing.JLabel crimeLabel1;
    private javax.swing.JButton exitTribunal;
    private javax.swing.JButton leftDoorButton;
    private javax.swing.JButton nextTrial;
    private javax.swing.JButton rightDoorButton;
    private javax.swing.JLabel verdict;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
